# Generated by Django 5.2.4 on 2025-07-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user_profile", "0002_token_tokenproxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="groups",
            field=models.ManyToManyField(related_name="user_profiles", to="auth.group"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="user_profiles", to="auth.permission"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
