# Generated by Django 3.2.25 on 2025-07-12 07:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
