# Generated by Django 3.2.25 on 2025-07-27 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userprofile_reputation'),
        ('questions', '0003_alter_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='user_profile.userprofile', to_field='username'),
        ),
    ]
