# Generated by Django 5.2.4 on 2025-07-12 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_profile", "0003_userprofile_groups_userprofile_is_superuser_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="comments",
                        to="user_profile.userprofile",
                    ),
                ),
            ],
        ),
    ]
