# Generated by Django 3.2.25 on 2025-07-12 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20250712_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='previous_comment',
            new_name='parent_comment',
        ),
    ]
