# Generated by Django 3.2.25 on 2025-07-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_rename_previous_comment_comments_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='votes', to='comments.comments'),
        ),
    ]
